---
title: "Lexical Diversity in Childes"
author: ' Yawen Yu and Dan Yurovsky'
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: null
  toc: no
number_sections: no
theme: lumen
code_folding: hide
toc_float: no
---

```{r,setup,echo=FALSE,message=FALSE}
#install packages
library(childesr)
library(data.table)
library(koRpus)
library(tidyverse)
load("~/Desktop/application/lexical diversity/trial 3/CHILDES_Lexical-diversity.RData")

#set language enviroment as english
set.kRp.env(lang = "kRp.env", validate = TRUE)
get.kRp.env(lang = TRUE, errorIfUnset = TRUE)
```


* Get and Clean Data 

```{r, message=FALSE,eval=FALSE}
# get partipants information
participants <- get_participants(role = "Target_child")


# get utterances of all children 
# convert age from days to months
child_data <- get_utterances(role = "Target_child") %>%
  mutate(speaker_age = speaker_age / 30.5)%>%
  mutate(target_child_age = target_child_age / 30.5)

# remove unintelligible utterances
murmur = c("xxx", "yyy", "yyy_yyy")

child_data_clean <- child_data %>%
  filter(!gloss %in% murmur) %>%
  mutate(gloss = removeWords(gloss, murmur),
         gloss = gsub("xxx", "", gloss),
         gloss = gsub("yyy", "", gloss)) %>%
  filter(!grepl("^\\s*$", gloss))
```



* Participants characteristic: children's age 

```{r, message=FALSE}
# only keep data of children who have age and id information
child_data_clean_age <- child_data_clean %>%
  mutate(age = if_else(is.na(speaker_age), target_child_age, speaker_age))  %>%
  filter(!is.na(age)) %>%
  filter(!is.na(speaker_id))

# most kids are at age 20~70 months
ggplot(child_data_clean_age, aes(x = age)) +
  geom_density()+
  theme_classic()
```



* Subset kids' data over time 

```{r, message=FALSE, eval=FALSE}
# get minimum age and maximum age of the dataset
min_age <- floor(min(child_data_clean_age$age))
max_age <- floor(max(child_data_clean_age$age))

# add a new column grouping every 6 months data of each kid
child_data_binned <- child_data_clean_age %>%
  mutate(age_bin = cut(age, breaks = seq(min_age, max_age, 6), ordered_result = TRUE))

# use corpus_id and speaker_id to distinguish individual child
corpus_id <- participants %>%
  distinct(corpus_id) %>%
  pull(corpus_id)

speaker_id <-participants %>%
  distinct(id) %>%
  pull(id)

child_data_collapsed <- child_data_binned %>%
  filter(corpus_id == corpus_id) %>%
  filter(speaker_id == speaker_id) %>%
  group_by(corpus_id, speaker_id, age_bin) %>%
  summarise(gloss = paste0(gloss, collapse = " ")) 

# only keep complete rows
child_data_collapsed <- child_data_collapsed[complete.cases(child_data_collapsed),]

# combine all gloss of each individual child at a certain age interval 
child_data_tokenized <- child_data_collapsed %>%
  split(paste0(.$corpus_id, "-", .$speaker_id, "-", .$age_bin)) 

```


* Measure children's LD over time 

```{r, message=FALSE, eval=FALSE}
# create a function to tokenize and measure diversity 
# with Measure of Textual Lexical Diversity(MTLD) 
tokenize_mtld <- function(df) {
  tokenized_df <- koRpus::tokenize(df$gloss, format = "obj", lang = "en", tag = TRUE)
  MTLD <- MTLD(tokenized_df)
  mtld <- data_frame(mtld = MTLD@MTLD$MTLD)
  length <- data_frame(length = MTLD@tt$num.tokens)
  merge(x = length,y = mtld, by = NULL)
}

# creat a function to measure diversity with Vocd-D
tokenize_vocd <- function(df) {
  tokenized_df <- koRpus::tokenize(df$gloss,format = "obj", lang = "en", tag = TRUE)
  VOCD <- HDD(tokenized_df)
  vocd <- data_frame(vocd =VOCD@HDD$HDD)
  length <- data_frame(length = VOCD@tt$num.tokens)
  merge(x = vocd, y = length)}
  

# combine children's information and measurement values
# remove unreliable results caused by extremely short speeches (tokens<100)
child_data_mtld <- map(child_data_tokenized, tokenize_mtld)%>% 
  bind_rows(.id = "id") %>%
  separate(col = id, into = c("corpus_id", "speaker_id", "age_bin"), sep = "-") %>%
  mutate(corpus_id = as.integer(corpus_id),
         speaker_id = as.integer(speaker_id)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100) 

child_data_vocd <- map(child_data_tokenized, tokenize_vocd)%>% 
  bind_rows(.id = "id") %>%
  separate(col = id, into = c("corpus_id", "speaker_id", "age_bin"), sep = "-") %>%
  mutate(corpus_id = as.integer(corpus_id),
         speaker_id = as.integer(speaker_id)) %>%
  filter(!length < 100) 


child_data_mtld <- child_data_mtld %>%
  mutate(age_bin = factor(age_bin, levels = levels(child_data_binned$age_bin))) 

child_data_vocd <- child_data_vocd %>%
  mutate(age_bin = factor(age_bin, levels = levels(child_data_binned$age_bin)))

# filter kids' records who have more than one measurement 
# so that we could know their development over time
mtld_filter <- function(df){
  nmtld <- aggregate(child_data_mtld$mtld, by = list(speaker_id = child_data_mtld$speaker_id), length)
  nchild <- nmtld$speaker_id[(nmtld$x != 1)]
  df <- df %>%
  filter(speaker_id %in% nchild)%>%
  group_by(speaker_id)
}

vocd_filter <- function(df){
  nvocd <- aggregate(df$vocd, by = list(speaker_id = df$speaker_id), length)
  nchild <- nvocd$speaker_id[(nvocd$x != 1)]
  df <- df %>%
  filter(speaker_id %in% nchild)%>%
  group_by(speaker_id)
}

child_mtld_dev <- mtld_filter(child_data_mtld)
child_vocd_dev <- vocd_filter(child_data_vocd)

# we capture 162 children's data in total
child_id_mtld <- unique(child_mtld_dev$speaker_id)
child_id_vocd <- unique(child_vocd_dev$speaker_id)


############################### Measure by months ##############################
# MTLD has an advantage of measuring texts subsequtially
# so let's measure every month data that is usually one coherent session
child_month_binned <- child_data_clean_age %>%
  mutate(age = round(speaker_age))


child_month_collapsed <- child_month_binned %>%
  filter(corpus_id == corpus_id) %>%
  filter(speaker_id == speaker_id) %>%
  group_by(corpus_id, speaker_id, age) %>%
  summarise(gloss = paste0(gloss, collapse = " ")) 

child_month_collapsed <- child_month_collapsed[complete.cases(child_month_collapsed),]

child_month_tokenized <- child_month_collapsed %>%
  split(paste0(.$corpus_id, "-", .$speaker_id, "-", .$age)) 

child_month_mtld <- map(child_month_tokenized, tokenize_mtld)%>% 
  bind_rows(.id = "id") %>%
  separate(col = id, into = c("corpus_id", "speaker_id", "age"), sep = "-") %>%
  mutate(corpus_id = as.integer(corpus_id),
         speaker_id = as.integer(speaker_id),
         age = as.numeric(age)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100) 

child_month_mtld <- mtld_filter(child_month_mtld)
```


* Measure mothers' LD over time 

```{r, message=FALSE,eval=FALSE}
# get partipants information
mom_participants <- get_participants(role = "Mother")

# get their utterances AND convert age from days to months
mom_data <- get_utterances(role = "Mother") %>%
  mutate(speaker_age = speaker_age / 30.5)%>%
  mutate(target_child_age = target_child_age / 30.5)

# remove unintelligible utterances
# only keep the records of moms who can be identified
mom_data_clean <- mom_data %>%
  filter(!gloss %in% murmur) %>%
  mutate(gloss = removeWords(gloss, murmur),
         gloss = gsub("xxx", "", gloss),
         gloss = gsub("yyy", "", gloss)) %>%
  filter(!grepl("^\\s*$", gloss)) %>%
  filter(target_child_id %in% child_id)

# subset by 6 months
mom_data_binned <- mom_data_clean %>%
  mutate(age_bin = cut(target_child_age, breaks = seq(min_age, max_age, 6)))

mom_data_collapsed <- mom_data_binned %>%
  filter(corpus_id == corpus_id) %>%
  filter(target_child_id == target_child_id) %>%
  group_by(corpus_id, target_child_id, age_bin) %>%
  summarise(gloss = paste0(gloss, collapse = " ")) 

mom_data_collapsed <- mom_data_collapsed[complete.cases(mom_data_collapsed),]
  
mom_data_tokenized <- mom_data_collapsed %>%
  split(paste0(.$corpus_id, "-", .$target_child_id, "-", .$age_bin)) 

# measure moms' LD by 6 months
## by MTLD
mom_data_mtld <- map(mom_data_tokenized,tokenize_mtld)%>% 
  bind_rows(.id = "id") %>%
  separate(col = id, into = c("corpus_id", "target_child_id", "age_bin"), sep = "-") %>%
  mutate(corpus_id = as.integer(corpus_id),
         speaker_id = as.integer(target_child_id)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100) 

## by Vocd-D
mom_data_vocd <- map(mom_data_tokenized, tokenize_vocd) %>%
  bind_rows(.id = "id") %>%
  separate(col = id,into = c("corpus_id", "target_child_id", "age_bin"),
  sep = "-" ) %>%
  mutate(corpus_id = as.integer(corpus_id),
  speaker_id = as.integer(target_child_id)) %>%
  filter(!length < 100)
  
mom_month_binned <- mom_data_clean %>%
  mutate(age_bin = cut(target_child_age,
  breaks = seq(min_age, max_age, 1),ordered_result = TRUE))

# measure moms' MTLD by month 
mom_month_binned <- mom_data_clean %>%
  mutate(age = round(target_child_age))

mom_month_collapsed <- mom_month_binned %>%
  filter(corpus_id == corpus_id) %>%
  filter(target_child_id == target_child_id) %>%
  group_by(corpus_id, target_child_id, age) %>%
  summarise(gloss = paste0(gloss, collapse = " ")) 

mom_month_collapsed <- mom_month_collapsed[complete.cases(mom_month_collapsed),]
  
mom_month_tokenized <- mom_month_collapsed %>%
  split(paste0(.$corpus_id, "-", .$target_child_id, "-", .$age)) 

mom_month_mtld <- map(mom_month_tokenized,tokenize_mtld)%>% 
  bind_rows(.id = "id") %>%
  separate(col = id, into = c("corpus_id", "target_child_id", "age"), sep = "-") %>%
  mutate(corpus_id = as.integer(corpus_id),
         speaker_id = as.integer(target_child_id),
         age = as.numeric(age)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100) 
```

* Plot children's LD  

```{r, message=FALSE}
mean_mtld <- mean(child_data_mtld$mtld)
mean_vocd <- mean(child_data_vocd$vocd)

# Note: the convergance after 50 months might relate to
# the large fluctuations of Vocd-D evaluating high LD texts
ggplot(child_vocd_dev, aes(x = age_bin, y = vocd,
  group = age_bin)) +
  geom_boxplot() +
  geom_smooth(method = loess) +
  theme_classic() +
  labs(title = "Vocd_D: Children's Lexical Diversity by 6 Months  ", subtitle = "3 ~ 147 Months")

ggplot(child_mtld_dev, aes(x = age_bin, y = mtld,
  group = age_bin)) +
  geom_boxplot() +
  geom_smooth(method = loess) +
  theme_classic()+
  labs(title = "MTLD: Children's Lexical Diversity by 6 Months", subtitle = "3 ~ 147 Months")

ggplot(child_month_mtld, aes(x = age, y = mtld,
  group = age)) +
  geom_boxplot(outlier.size = 0.5) +
  geom_smooth(method = loess, se = FALSE) +
  xlim(3, 147) +
  theme_classic() +
  labs(title = "MTLD: Childrens' Lexical Diversity by Month", subtitle = "3 ~ 147 Months")

```


* Plot Moms' LD 

```{r, message=FALSE}
# MTLD results show greater disparity among moms than Vocd_D, which is very puzzling
mean_mtld_mom <- mean(mom_data_mtld$mtld)
mean_vocd_mom <- mean(mom_data_vocd$vocd)
mean_mtld_mom_month<- mean(mom_month_mtld$mtld)

ggplot(mom_data_vocd, aes(x = vocd))+
  geom_histogram()+
  geom_vline(xintercept = mean_vocd_mom, colour = "gold", size = 2)+
  theme_classic()+
  labs(title = " Histogram of Moms' Vocd_D by 6 Months")

ggplot(mom_data_mtld, aes(x = mtld))+
  geom_histogram()+
  geom_vline(xintercept = mean_mtld_mom, colour = "gold", size = 2)+
  theme_classic()+
  labs(title = " Histogram of Moms' MTLD by 6 Months")

ggplot(mom_month_mtld, aes(x=mtld))+
  geom_histogram(bins=30)+
  theme_classic()+
  labs(title = " Histogram of Moms' MTLD by Month")

ggplot(mom_data_vocd,aes(x=age_bin,y=vocd))+
      geom_boxplot()+
      labs(title = " Vocd_D: Moms' Lexical Diversity of Mothers by 6 Months")+
      theme_classic()

ggplot(mom_data_mtld,aes(x=age_bin,y=mtld))+
      geom_boxplot()+
      labs(title = " MTLD: Moms' Lexical Diversity of Mothers by 6 Months")+
      theme_classic()

ggplot(mom_month_mtld,aes(x=age,y=mtld, 
                          group = age))+
      geom_boxplot(outlier.size = 0.5)+
      xlim(0,150)+
      labs(title = " MTLD: Moms' Lexical Diversity of Mothers by Month")+
      theme_classic()
```



* Any relation between mothers' LD with their children's LD? 

```{r, message=FALSE}
## combine data of moms and their children, 134 in total
mom_id <- unique(mom_month_mtld$target_child_id)
combine_month_mtld <- child_month_mtld %>%
  filter(speaker_id %in% mom_id) 

combine_month_mtld <-
  merge(x = combine_month_mtld,
  y = mom_month_mtld[, c("speaker_id", "age", "length", "mtld")],
  by = c("speaker_id", "age"))

## look at change of children's LD
combine_month_mtld_dif <- child_month_mtld %>%
  filter(speaker_id %in% mom_id) %>%
  group_by(speaker_id) %>%
  mutate(change = lag(mtld))

combine_month_mtld_dif <-
  merge(x = combine_month_mtld_dif,
  y = mom_month_mtld[, c("speaker_id", "age", "length", "mtld")],
  by = c("speaker_id", "age"))


# linear regression
# only children's and mothers' MTLD
lm_child_mom <- lm(mtld.x ~ mtld.y, combine_month_mtld)
summary(lm_child_mom)


# add another variable log(age)
lm_child_mom_lg <-lm(mtld.x ~ mtld.y + log(age),combine_month_mtld)
summary(lm_child_mom_lg)
plot(fitted(lm_child_mom_lg), residuals(lm_child_mom_lg))


# children's development and mothers' MTLD
lm_child_mom_dif <- lm(change ~ mtld.y, combine_month_mtld_dif)
summary(lm_child_mom_dif)


# moms' and children's LD at 24 months
## 69 kids
combine_child_mom_24 <- combine_month_mtld[which(combine_month_mtld$age == 24),]
lm_child_mom_24 <- lm(mtld.x ~ mtld.y, combine_child_mom_24)
summary(lm_child_mom_24)
plot(fitted(lm_child_mom_24), residuals(lm_child_mom_24))


# moms' and children's LD at 30 months
## 65 kids
combine_child_mom_30 <- combine_month_mtld[which(combine_month_mtld$age == 30),]
lm_child_mom_30 <- lm(mtld.x ~ mtld.y, combine_child_mom_30)
summary(lm_child_mom_30)
plot(fitted(lm_child_mom_30), residuals(lm_child_mom_30))


#MTLD measurement associates with utterance length
## need to control for length
summary(lm(mtld.x ~ length.x,combine_month_mtld))

```
