---
title: "childes_ld"
author: "Yawen Yu and Dan Yurovsky"
date: "2/7/2018"
output:
  html_document: default
  pdf_document: default
---

```{r, library, message=F,results='hide', warning=FALSE, echo=F}
# Library required packages
library(feather)
library(koRpus)
library(tidyverse)
library(tm)
library(lme4)
library(dplyr)
library(childesr)
library(sjPlot)
```


```{r, message=FALSE, echo=FALSE}
# get information of all participants
participants <- get_participants(collection = NULL,
corpus = NULL, child = NULL, role = NULL)
```


```{r, eval=F, message=FALSE, echo=FALSE}
# Clean Data and Assess Lexical Diversity 
# get utterances 
utter <- get_utterances(
collection = NULL, corpus = NULL,
child = NULL, role = NULL) %>%
  filter(language == "eng")

# remove unintelligible utterances
murmur = c("xxx", "yyy", "yyy_yyy","---")

utter_kid <- utter %>%
  filter(speaker_code == "CHI") %>%
  filter(!stem %in% murmur) %>%
  mutate(stem = removeWords(stem, murmur),
         stem = gsub("[^[:alnum:]]", " ", stem)) %>%
  filter(!grepl("^\\s*$", stem)) 

utter_p <- utter %>%
  filter(speaker_code == c("MOT","FAT")) %>%
  filter(!stem %in% murmur) %>%
  mutate(stem = removeWords(stem, murmur),
         stem = gsub("[^[:alnum:]]", " ", stem)) %>%
  filter(!grepl("^\\s*$", stem)) 
 

# collapse utterances of child at one month to one row
kid_collapsed <- utter_kid %>%
  filter(corpus_id == corpus_id) %>%
  filter(speaker_id == speaker_id) %>%
  filter(target_child_age == target_child_age) %>%
  filter(transcript_id == transcript_id) %>%
  group_by(corpus_id, speaker_id, target_child_age, transcript_id) %>%
  summarise(utts = paste0(stem, collapse = " ")) %>%
  mutate(age = floor(target_child_age/30.5)) %>%
  ungroup(.)%>%
  select(-target_child_age)%>%
  rename(corpus = corpus_id, subject = speaker_id,
         session = transcript_id) 

# tokenize child's speech 
kid_tokenized <- kid_collapsed %>%  
  ungroup(.) %>%
  filter(complete.cases(.)) %>%
  split(paste0(.$corpus, "-",.$subject, "-", .$age, "-"))  
 

# tokenize utterances of caregiver 
p_tokenized <- utter_p %>%
  filter(corpus_id == corpus_id) %>%
  filter(transcript_id == transcript_id) %>%
  filter(target_child_age == target_child_age) %>%
  group_by(corpus_id, transcript_id, target_child_age) %>%
  summarise(utts = paste0(stem, collapse = " ")) %>%
  mutate(age = floor(target_child_age/30.5)) %>%
  select(-target_child_age) %>%
  rename(corpus = corpus_id, session = transcript_id) %>%
  left_join(select(kid_collapsed, corpus, subject, session, age)) %>%
  ungroup(.) %>%
  filter(complete.cases(.)) %>%
  split(paste0(.$corpus, "-",.$subject, "-", .$age, "-")) 
  

# create a function to measure lexical diversity with MTLD
mtld_fun <- function(df) {
  tokenized_df <- koRpus::tokenize(df$utts, format = "obj", lang = "en", tag = TRUE) #tokenize texts
  MTLD <- MTLD(tokenized_df)# measure LD
  mtld <- data_frame(mtld = MTLD@MTLD$MTLD) # get LD measurement
  length <- data_frame(length = MTLD@tt$num.tokens)  # get length meaasurement
  merge(x = length,y = mtld, by = NULL) # combine LD and lenghth values
}


# measure speech of child and caregiver 
kid_ld <- map(kid_tokenized, mtld_fun) %>% 
  bind_rows(.id = "subject") %>%
  separate(col = subject, into = c("corpus","subject", "age"), sep = "-") %>%
  mutate(corpus = as.numeric(corpus),
         subject = as.numeric(subject),
         age = as.numeric(age)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100) # MTLD yield inaccurate results if utterance length <100 words


p_ld <- map(p_tokenized, mtld_fun) %>% 
  bind_rows(.id = "subject") %>%
  separate(col = subject, into = c("corpus","subject", "age"), sep = "-") %>%
  mutate(corpus = as.numeric(corpus),
         subject = as.numeric(subject),
         age = as.numeric(age)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100)


# filter kids' data with more than 5 observeations
mtld_filter <- function(df) {
  nmtld <- aggregate(df$mtld, by = list(subject = df$subject),length)
  nchild <- nmtld$subject[(nmtld$x > 5)]
  df <- df %>%
  filter(subject %in% nchild) %>%
  group_by(subject)
  
  return(df)
}


all_data <- mtld_filter(kid_ld) %>%
  left_join(y = mtld_filter(p_ld), by = c("corpus", "subject", "age")) %>%
  ungroup() %>%
  filter(complete.cases(.)) %>%
  filter(age <100) %>%
  rename(kid_mtld = mtld.x,
         kid_length = length.x,
         mom_mtld = mtld.y,
         mom_length = length.y) %>%
  left_join(y = rename(participants, subject = id)) %>%
  filter(!subject == 5221)# utterance is coded in an unintelligible way


# write kid data to disk
write_feather(all_data, "/Users/Yawen/Desktop/lexical diversity/trial6_childes/all_data.feather")
```


```{r, message=FALSE, echo=F}
all_data <- read_feather("/Users/Yawen/Desktop/lexical diversity/trial6_childes/all_data.feather")

# child's mtld as a function of age
age_model <- lmer(kid_mtld ~ 1 + log(age) + (1+log(age)|subject), data = all_data)

# get child's slope
fixed_effects <- fixef(age_model) 
ran_effects <- as_data_frame(ranef(age_model)$subject) 
kid_effects <-  ran_effects %>%
  mutate(subject = as.integer(rownames(ran_effects)),
         kid_slope = `log(age)` + fixed_effects[2]) %>%
  select(subject, kid_slope)

# child's predicted mtld at 20 month as intercept
kid_data <- kid_effects %>%
  mutate(age = 20)%>%
  mutate(kid_intercept = predict(age_model, newdata = .)) %>%
  select(-c(age))

# get mother's intercept at 20 month and slope
mom_slope_model <- lmer(mom_mtld ~  1+ log(age) + (1 + log(age)|subject), data = all_data)

mom_fix <- fixef(mom_slope_model) 
mom_random <- as_data_frame(ranef(mom_slope_model)$subject) 
mom_effects <-  mom_random %>%
  mutate(subject = as.integer(rownames(mom_random)),
         mom_slope = `log(age)` + mom_fix[2]) %>%
  select(subject, mom_slope) %>%
  mutate(age = 20) %>%
  mutate(mom_intercept = predict(mom_slope_model, newdata = .))  %>%
  select(-c(age))

# merge child and mother data
model_data <- participants %>%
  rename(subject = id) %>%
  left_join(x=mom_effects) %>%
  left_join(x=kid_data)

full_data <- all_data %>%
  left_join(mom_effects) %>%
  left_join(kid_data)

```


### Model Growth Trajectory
```{r}
# 1) kid's intercept (20 months) as response
## mother language
summary(lm(kid_intercept ~  mom_intercept + mom_slope, data = model_data))

## gender*
model_data %>%
  filter(!is.na(sex)) %>%
  lm(kid_intercept ~ mom_intercept + mom_slope + sex, data = .) %>%
  summary() #41 kids

## gender + SES
model_data %>%
  filter(!is.na(ses)) %>%
  filter(!is.na(sex)) %>%
  lm(kid_intercept ~ mom_intercept + mom_slope + ses + sex, data = .)  #17 kids




# 2) kid's slope as response
## mother language
slope_model <- lm(kid_slope ~  mom_slope + mom_intercept, data = model_data)


## gender*
model_data %>%
  filter(!is.na(sex)) %>%
  lm(kid_slope ~ mom_intercept + mom_slope + sex, data = .) %>%
  summary() 

## gender + kid_intercept*
model_data %>%
  filter(!is.na(sex))%>%
  lm(kid_slope ~ mom_intercept + mom_slope + kid_intercept +sex, data = .) %>%
  summary() 

## kid's intercept**
model_data %>%
  lm(kid_slope ~ mom_intercept + mom_slope + kid_intercept, data = .) %>%
  summary() 

## SES + kid_intercept***
model_data %>%
  filter(!is.na(ses)) %>%
  lm(kid_slope ~ mom_intercept + mom_slope + ses + kid_intercept, data = .) %>%
  summary()



# 3) mother's intercept as response
lm(mom_intercept ~ kid_intercept, data = model_data)


## SES*
model_data %>%
  filter(!is.na(ses)) %>%
  lm(mom_intercept ~ kid_intercept + ses, data = .) %>%
  summary() #27 kids

## gender + SES**
model_data %>%
  filter(!is.na(sex)) %>%
  filter(!is.na(ses))%>%
  lm(mom_intercept ~ kid_intercept + sex + ses, data = .) %>%
  summary() #17 kids



# 4) General growth trajectory varies by mother's diversity of speech
## low:32; median: 32; high:42
full_data %>%
  ungroup()%>%
  mutate(rank = ifelse(mom_intercept <= quantile(mom_intercept, probs=c(0.30)), 0, 
                       ifelse(mom_intercept <= quantile(mom_intercept, probs=c(0.60)), 1,2)),
         rank = as.factor(rank)) %>%
  group_by(subject) %>%
  ggplot(.,aes(x=age, y=kid_mtld, color=rank))+
  geom_smooth(se=F)+
  theme_classic()+
  scale_x_log10()

summary(lm(kid_mtld ~ mom_intercept + mom_slope, data = full_data))
summary(lm(scale(kid_mtld) ~ scale(mom_intercept) + scale(mom_slope), data = full_data))
```
