---
title: "Fitting Models"
author: 'Yawen Yu and Dan Yurovsky'
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: null
  toc: no
number_sections: no
theme: lumen
code_folding: hide
toc_float: no
---


```{r, global chunck options, include=FALSE,eval=FALSE}
knitr::opts_chunk$set(message=FALSE, results='markup',warning =  FALSE)
options(xtable.comment=FALSE)
```
```{r, setup, eval=FALSE, warning=FALSE}
library(mice)
library(tidyverse)
library(lme4)
library(tseries)
library(forecast)
load("~/Desktop/application/lexical diversity/trial_3_pre/CHILDES_Lexical-diversity.RData")
```

## Prepare data
```{r}
# filter kids with more than 2 observations
mtld_filter <- function(df) {
  nmtld <- aggregate(child_data_mtld$mtld,
  by = list(speaker_id = child_data_mtld$speaker_id),
  length)
  nchild <- nmtld$speaker_id[(nmtld$x > 2)]
  df <- df %>%
  filter(speaker_id %in% nchild) %>%
  group_by(speaker_id)
}

child_month_dev <- mtld_filter(child_month_mtld)

# combine mom and child data
combine_month_dev <- child_month_dev %>%
  filter(speaker_id %in% mom_id) %>%
  group_by(speaker_id) %>%
  rename(mtld.x = mtld,
         length.x = length) %>%
  left_join(select(mom_month_mtld, -target_child_id)) %>%
  rename(mtld.y = mtld,
         length.y = length) %>%
  group_by(corpus_id, speaker_id) %>%
  arrange(corpus_id, speaker_id, age) 

# keep complete records
combine_month_dev <- combine_month_dev[complete.cases(combine_month_dev),]
#check redisual plot
test_model <- lm(mtld.y ~ log(age),combine_month_dev)
plot(test_model) 

# filter kids with more than 5 observations
mtld_filter <- function(df) {
  nmtld <- aggregate(child_data_mtld$mtld,
  by = list(speaker_id = child_data_mtld$speaker_id),
  length)
  nchild <- nmtld$speaker_id[(nmtld$x > 5)]
  df <- df %>%
  filter(speaker_id %in% nchild) %>%
  group_by(speaker_id)
}

combine_month_dev5 <- mtld_filter(combine_month_dev)

# data transformation and get lagged data (up to 5 months)
combine_month_trans <- combine_month_dev5 %>%
  mutate(mtld.y = log2(mtld.y),
         mtld.x = sqrt(mtld.x),
         lag.x = lag(mtld.x),
         lag.y = lag(mtld.y),
         lag.x2 = lag(mtld.x, n=2),
         lag.y2 = lag(mtld.y, n=2),
         lag.x3 = lag(mtld.x,n=3),  
         lag.y3 = lag(mtld.y, n= 3),
         lag.x4 = lag(mtld.x,n=4),  
         lag.y4 = lag(mtld.y,n=4),
         lag.x5 = lag(mtld.x,n=5),
         lag.y5 = lag(mtld.y, n=5))
```


## Examine correlation between moms' LD and children's LD 
* not control for age 
```{r}
# Simple model: children's LD versus mothers' LD
lm_child_mom <- lm(mtld.x ~ mtld.y, combine_month_mtld)
summary(lm_child_mom)

# add another variable log(age)
lm_child_mom_lg <-lm(mtld.x ~ mtld.y + log(age),combine_month_mtld)
summary(lm_child_mom_lg)
plot(fitted(lm_child_mom_lg), residuals(lm_child_mom_lg))


# Since correlation is always significant in a large dataset 
# let's look at moms' and children's LD at 24 months (69 kids)
combine_child_mom_24 <- combine_month_mtld[which(combine_month_mtld$age == 24),]
lm_child_mom_24 <- lm(mtld.x ~ mtld.y, combine_child_mom_24)
summary(lm_child_mom_24)
plot(fitted(lm_child_mom_24), residuals(lm_child_mom_24))

# moms' and children's LD at 30 months (65 kids)
combine_child_mom_30 <- combine_month_mtld[which(combine_month_mtld$age == 30),]
lm_child_mom_30 <- lm(mtld.x ~ mtld.y, combine_child_mom_30)
summary(lm_child_mom_30)
plot(fitted(lm_child_mom_30), residuals(lm_child_mom_30))

ggplot(combine_month_mtld,aes(mtld.y,mtld.x,color = speaker_id))+
  geom_point()+
  geom_smooth(method = "gam")+
  theme_classic()

# Results: All of models above show significant correlation between moms' LD and children's LD
# Next step: To examnine this correlation by controlling for age 
```


## Granger Causality model 
```{r,message=F}
# 1) filter kids with observations during 20~35 months 
# 2) drop kids with more than 20% missing values 
filter_id <- function(df){
freq_age <- aggregate(df$mtld.x, by = list(age = df$age), length) 
df <- df[which(df$age > 19 & df$age < 36),]
df <- df[,c("speaker_id","age","mtld.x")]
number <- aggregate(df$mtld.x, by = list(speaker_id = df$speaker_id), length)
id <- number$speaker_id[which(number$x > (0.8 *16))]
df <- df %>%
  filter(speaker_id %in% id)
}

# get 14 kids in total
filter_child <- filter_id(combine_month_mtld)
id <- unique(filter_child$speaker_id) 

# 3)impute missing data
wide_data <- function(df){
df <- reshape(df , idvar = "age" , timevar = "speaker_id", direction = "wide")
df <- df[order(df$age),]
colnames(df) <- c("age",id)
df
}

filter_child_wide <- wide_data(filter_child)

set.seed(500)
md.pattern(filter_child_wide)
impute_data <- mice(filter_child_wide,m=5,maxit=5,meth='pmm',seed=500)
summary(impute_data)
impute_data <- mice::complete(impute_data,1)

# convert to long format
long_data <- function(df){
age <- df$age
df <- gather(df, age, value, colnames(df[,2:15]), factor_key = TRUE)
colnames(df) <- c("age","speaker_id","mtld")
df
}

filter_child_impute <- long_data(filter_child_wide)

# combine imputed child data with moms
filter_combine <- merge(x = filter_child_impute,
  y = combine_month_mtld[, c("speaker_id", "age", "mtld.y")],
  by = c("speaker_id", "age"))

# 4) use Dickey-Fuller Test to check stationarity
tseries::adf.test(filter_combine$mtld, alternative = "stationary", k=0) # p-value < 0.05 indicates it is stationary

# 5) examine with Granger Casuality Model
# H0: development of kids' LD is independent of change of moms' LD
# Ha: development of kids' LD is dependent on change of moms' LD
kid_lag <- diff(filter_combine$mtld)
mom_mtld <- diff(filter_combine$mtld.y)
# we do not get enough evidence to reject the null hypothesis
lmtest::grangertest(kid_lag~mom_mtld, order = 2)
```


## Examine cocurrent correlations bwteen moms and children
```{r,message=F}
# Take age as fixed effect and moms' LD as random effect
lmer_lg <-
  lmer(scale(mtld.x) ~ log(age) + (scale(mtld.y)|speaker_id), 
       data = combine_month_trans) # scale the MTLD values since kids normally have slighly lower LD
summary(lmer_lg)

# Take moms' LD as fixed effect and age as random effect
lmer_child_mom_lg <-
  lmer(scale(mtld.x) ~ scale(mtld.y) - 1  + log(age) +
  (1 + log(age) | speaker_id),
  combine_month_mtld) 

summary(lmer_child_mom_lg)

ggplot(fortify(lmer_child_mom_lg),aes(mtld.y, mtld.x, 
                                 color = speaker_id)) +
       stat_summary(aes(y = .fitted), fun.y = mean, geom = "line")

```


## Examine influences of moms with low/moderate/high LD 
```{r,message=F}
# group moms according to LD levels (low/moderate/high)
mu_mom <- mean(combine_month_dev$mtld.y,na.rm=TRUE)
sd_mom <- sd(combine_month_dev$mtld.y, na.rm=TRUE)
low <- mu_mom -  0.5 * sd_mom
high <- mu_mom +  0.5 * sd_mom

ggplot(combine_month_mtld,aes(mtld.y))+
  geom_histogram(bins = 30)+
  geom_vline(xintercept = low, color = "gold",size = 2)+
  geom_vline(xintercept = high, color = "gold",size = 2)

mom_dif = cut(combine_month_dev$mtld.y,
  breaks = c(14, low, high, 125),
  label = c("low", "moderate", "high"))

# high level moms better correlated with kids' development
lm_mom_dif <-lm(mtld.x ~  mom_dif , combine_month_dev)
summary(lm_mom_dif)

lmer_mom_dif <-lmer((mtld.x - lag.x) ~  mom_dif + (1 | speaker_id), combine_month_dev)
summary(lmer_mom_dif)

# add age variable as one fixed effect
lmer_dif_age <- lmer((mtld.x - lag.x) ~   mom_dif + log(age) + 
                       (1 | speaker_id), combine_month_dev)
summary(lmer_dif_age)
```


## ARMA model
```{r,results= 'hide'}
# build simple ARMA model using lm
lm_dev <- lm(mtld.x ~ lag.x + (1+lag.x) * factor(speaker_id) , data = combine_month_trans)
summary(lm_dev)

# fit ARMA model
# check stationarity
adf.test(combine_month_trans$mtld.x) #p-value<0.05

# autocorrelation plot: shows spikes at lags 1 and 2
acf(combine_month_trans$mtld.x)
pacf(combine_month_trans$mtld.x)

# choose ARMA model for lag=1
model_d1 <-diff(combine_month_trans$mtld.x, differences = 1)
plot(model_d1)
adf.test(model_d1)
acf(model_d1) #shows spikes at lag 1,2
pacf(model_d1) 
auto.arima(model_d1, seasonal = FALSE)

# choose ARMA model for lag=2
model_d2 <-diff(combine_month_trans$mtld.x, differences = 2)
plot(model_d2)
adf.test(model_d2)
acf(model_d2)
pacf(model_d2) 
auto.arima(model_d2, seasonal = FALSE)

# Note: by comparison, we can better predict mtld.x with first ARMA model when lag=1
```


## Examine correlations between moms' changing slope and kids' LD 
```{r,message=F}
###### 1) model: moms' slope over time Vs. kids' LD over time #####
# get growth slope (long-term) for each kid
kid_slope <-lmer(mtld.x ~ (age | speaker_id), data = combine_month_trans)

kid_growth <- data.frame(coef(kid_slope)$speaker_id) %>%
  mutate(speaker_id = child_id) %>%
  select(speaker_id,X.Intercept.,age) 

# get changing slope (long-term) for each mom
mom_slope <- lmer(mtld.y ~ (age | speaker_id), data = combine_month_trans)

combine_growth <- data.frame(coef(mom_slope)$speaker_id) %>%
  mutate(speaker_id = child_id) %>%
  select(speaker_id,X.Intercept.,age)%>%
  left_join(kid_growth, by = "speaker_id")

# no significant correlation bewteen moms' and children's slope
summary(lm(age.x ~ age.y, data=combine_growth))


####### 2) model: mom's slope at month [t-4,t] Vs.kid's LD at month t ###
#temp: build model based on one kid & mom (age:27~69)
one <- combine_month_trans %>%
  filter(speaker_id == "532")

# get changing slope over time 
one_slope <- data.frame(age = one$age, mtld.x = one$mtld.x,slope.y = NA)

for(i in (4:nrow(one))){
  mom_lag <- data.frame(age = one[1:i,"age"], mtld.y = one[1:i,"mtld.y"], mtld.x = one$mtld.x[[i]]) 
  one_slope[i,"slope.y"] <- coef(lm(mtld.y ~ age, mom_lag))[[2]]
}

# highly negative correlation
summary(lm(mtld.x ~ slope.y, one_slope))

####### 3) apply the model to 27 children #####
child_id <- unique(combine_month_trans$speaker_id)
combine_slope <- data.frame()
            
for(i in (1:length(child_id))){
  one_kid <- combine_month_trans[,c("speaker_id","age","mtld.x","mtld.y")]%>%
    mutate(slope.y = NA)%>%
    filter(speaker_id == child_id[[i]])
  for(t in (4:nrow(one_kid))){
  one_mom <- data.frame(age = one_kid[1:t,"age"], mtld.y = one_kid[1:t,"mtld.y"], mtld.x = one_kid$mtld.x[[t]]) 
  one_kid[t,"slope.y"] <- coef(lm(mtld.y ~ age, one_mom))[[2]]
  }
  combine_slope <- bind_rows(combine_slope, one_kid)
}

# highly negative correlation
summary(lm(mtld.x ~ slope.y, combine_slope))

```



