---
title: "LDP_LD"
author: 'Yawen Yu and Dan Yurovsky'
date: "12/5/2017"
output: pdf_document
---
## Load Data & Clean Data
```{r, load data, message=FALSE, echo=TRUE}
library(sjPlot)
library(koRpus)
library(tidyverse)
library(tm)
library(lme4)
library(dplyr)

# Read in LDP data
ldp <- src_sqlite("/Users/Yawen/Desktop/application/lexical diversity/trial5_ldp/ldp.db")

# Get all utterances
utter <- tbl(ldp, "utterances") %>%
  collect() 

# Get all participants
subjs <- tbl(ldp, "subjects") %>%
  collect() %>%
  rename(subject = id)

# Get visit data
visits <- tbl(ldp, "visits") %>%
  collect() %>%
  select(subject, session, date, child_age, child_age_years, child_age_months,
         income)

# Get measures data
measures <- tbl(ldp, "measures") %>%
  collect() %>%
  select(-last_update) %>%
  left_join(y=visits, by = c("subject", "session")) %>%
  mutate(ttr = word_types/word_tokens) 
```

## Clean utterance data
```{r, clean data, results='hide', message=FALSE}
# remove unintelligible utterances
murmur = c("xxx", "yyy", "yyy_yyy","---")
utter_clean <- utter %>%
  filter(!c_utts %in% murmur) %>%
  mutate(c_utts = removeWords(c_utts, murmur),
         c_utts = gsub("[^[:alnum:]]", " ", c_utts)) %>%
  filter(!grepl("^\\s*$", c_utts)) 


#### Alert: Age column is NOT completely coded, but Session column is complete
## complete missing Age data according to Session data
session_80 <- visits %>%
  filter(session > 12) %>%
  mutate(age = round(mean(child_age_months))) %>%
  select("session", "age") %>%
  unique(.)

session_age <- measures %>%
  select("session", "child_age_months") %>%
  mutate(child_age_months = round(child_age_months)) %>%
  rename(age = child_age_months) %>%
  unique(.) %>%
  head(n=12) %>%
  rbind(session_80)

# collapse utterances at one month to one row
utter_collapsed <- utter_clean %>%
  filter(subject == subject) %>%
  filter(session == session) %>%
  group_by(subject, session) %>%
  summarise(utts = paste0(c_utts, collapse = " ")) 

# keep only complete rows
utter_tokenize <- utter_collapsed[complete.cases(utter_collapsed),] %>%
                        split(paste0(.$subject, "-", .$session, "-"))  

```

## Measure Child's Lexical Diversity
```{r,measure lexical diversity, results='hide', message=FALSE}
##### TTR is not very informative
measures %>%
  filter(speaker == "C") %>%
  ggplot(aes(x=session, y=ttr)) +
  geom_smooth(se = F) +
  theme_classic()

# measure LD with MTLD
tokenize_mtld <- function(df) {
  tokenized_df <- koRpus::tokenize(df$utts, format = "obj", lang = "en", tag = TRUE) #tokenize texts
  MTLD <- MTLD(tokenized_df) # measure LD
  mtld <- data_frame(mtld = MTLD@MTLD$MTLD) # get LD measurement
  length <- data_frame(length = MTLD@tt$num.tokens)  # get length meaasurement
  merge(x = length,y = mtld, by = NULL) # combine LD and lenghth values
}

# measure and filter accurate data
utter_ld <- map(utter_tokenize, tokenize_mtld)%>% 
  bind_rows(.id = "id") %>%
  separate(col = id, into = c("subject", "session"), sep = "-") %>%
  mutate(subject = as.integer(subject),
         session = as.integer(session)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100) # MTLD yield inaccurate results when utterance length <100 words

# filter kids' data with more than 2 observeations
mtld_filter <- function(df) {
  nmtld <- aggregate(df$mtld,
  by = list(subject = df$subject),length)
 
   nchild <- nmtld$subject[(nmtld$x > 2)]
  
  df <- df %>%
  filter(subject %in% nchild) %>%
  group_by(subject)
  
  return(df)
}

filter_data <- mtld_filter(utter_ld) 
```

## Measure Mother's Lexical Diversity
```{r}
# remove unintelligible utterances
utter_mom <- utter %>%
  filter(!p_utts %in% murmur) %>%
  mutate(p_utts = removeWords(p_utts, murmur),
         p_utts = gsub("[^[:alnum:]]", " ", p_utts)) %>%
  filter(!grepl("^\\s*$", p_utts)) %>%
  select(subject, session, p_utts)%>%
  left_join(x=session_age, by = c("session")) 

# collapse each month's utterances to one row
mom_col <- utter_mom %>%
  group_by(subject, session, age) %>%
  summarise(utts = paste0(p_utts, collapse = " "))

# keep only complete rows
mom_tok <- mom_col[complete.cases(mom_col),] %>%
  split(paste0(.$subject, "-", .$session, "-", .$age))  

mom_ld <- map(mom_tok, tokenize_mtld)%>% 
  bind_rows(.id = "id") %>%
  separate(col = id, into = c("subject", "session"), sep = "-") %>%
  mutate(subject = as.integer(subject),
         session = as.integer(session)) %>%
  filter(!mtld == as.numeric("inf")) %>%
  filter(!length < 100) 

mom_data <- mtld_filter(mom_ld)
```


## Merge Children's and Mother's data
```{r}
# original data
complete_data <- filter_data %>%
  left_join(y = mom_data,by = c("subject", "session")) %>%
  rename(kid_mtld = mtld.x,
         kid_length = length.x,
         mom_mtld = mtld.y,
         mom_length = length.y) %>%
  left_join(y = session_age, by = c("session")) %>%
  left_join(y = subjs, by = c("subject")) %>%
  filter(lesion == "") %>% ## keep data of typically-developing children
  left_join(visits) %>%
  group_by(subject) %>%
  mutate(income = replace(income, is.na(income), round(mean(income, na.rm = T))))  %>%
  ungroup(.) %>%
  filter(complete.cases(.)) %>%
  select(subject, session, age, kid_length, kid_mtld, mom_length, mom_mtld, sex, race, ethn, income)


## 66 kids in total
id <- unique(complete_data$subject)
```


## Model Growth Trajectory
```{r}
# Model1: child's lexical diversity as response
null_model <- lmer(kid_mtld ~ 1 + (1 |subject), data = complete_data)
age_model <- lmer(kid_mtld ~ 1 + log(age) + (1+log(age)|subject), data = complete_data)
anova(null_model, age_model)

gender_model <- lmer(kid_mtld ~ 1 + log(age) + sex + (1+log(age)|subject), data = complete_data)
anova(age_model, gender_model) # gender is not good predictor of kid_mtld

eth_model <- lmer(kid_mtld ~ 1 + log(age) + race + (1+log(age)|subject), data = complete_data)
anova(age_model, eth_model) # race is not a good predictor

income_model <- lmer(kid_mtld ~ 1 + log(age) + (1|income) + (1+log(age)|subject), data = complete_data)
anova(age_model, income_model) # income is not a good predictor

# summary optimal model
Model1 <-age_model
summary(Model1)


# get kid's slope based on Model1
fixed_effects <- fixef(Model1) 
ran_effects <- as_data_frame(ranef(Model1)$subject) 
kid_effects <-  ran_effects %>%
  mutate(subject = as.integer(rownames(ran_effects)),
         kid_slope = `log(age)` + fixed_effects[2]) %>%
  select(subject, kid_slope)


# plot predicted lexical diversity growth 
predict_data <- complete_data %>%
  mutate(predicted = predict(Model1, newdata =.)) 

ggplot()+
  geom_smooth(aes(x = age, y = mom_mtld, color = "mother's observed data"),se = FALSE, data = predict_data)+
  geom_smooth(aes(x=age, y=kid_mtld, color = "child's observed data"),se = FALSE, data = predict_data)+
  geom_smooth(aes(x=age, y=predicted, color = "child's predicted data"),se = FALSE, data = predict_data)+
  labs(title = "Childrens' and Mothers' Lexical Diversity Growth", subtitle = "0 ~ 138 Months") +
  theme_classic() +
  ylab("Lexical Diversity")+
  xlab("Age (month)") +
  scale_x_log10()
```


# Revised Part
## Get Estimated Intercept 
```{r, modeling, message=FALSE}
# Child's predicted mtld value at 20 month as intercept
kid_data <- kid_effects %>%
  mutate(age = 20)%>%
  mutate(kid_intercept = predict(Model1, newdata = .)) %>%
  select(-c(age))

# predict mother's intercept at 20 month  
mom_slope_model <- lmer(mom_mtld ~  1+ log(age) + (1 + log(age)|subject), data = complete_data)

mom_fix <- fixef(mom_slope_model) 
mom_random <- as_data_frame(ranef(mom_slope_model)$subject) 
mom_effects <-  mom_random %>%
  mutate(subject = as.integer(rownames(mom_random)),
         mom_slope = `log(age)` + mom_fix[2]) %>%
  select(subject, mom_slope) %>%
  mutate(age = 20) %>%
  mutate(mom_intercept = predict(mom_slope_model, newdata = .))  %>%
  select(-c(age))


# combine data
all_data <- kid_data %>%
  left_join(mom_effects) %>%
  left_join(complete_data) %>%
  group_by(subject)

```  


## Model2: Child Intercept as Repsonse
```{r}
null <- lm(kid_intercept ~ 1 , data = all_data)
full <- lm(kid_intercept ~ mom_slope + mom_intercept + sex + race + income, data = all_data)
step(null, scope=list(lower=null, upper=full), direction="both", na.rm = TRUE)

## summarize model
Model2 <- lm(kid_intercept ~ mom_slope + mom_intercept + income, data = all_data)

summary(Model2)

sjt.lmer(Model2, show.header = TRUE, string.est = "Estimate", 
         string.ci = "Conf. Int.", string.p = "p-value",
         string.dv = "Response", string.pred = "Coefficients",
         p.numeric = F)


# Plot 
ggplot(all_data, aes(x = mom_intercept, y = kid_intercept))+
  geom_smooth(se=F)+
  theme_classic()+
  labs(title = "Relationship between Intercept of Mothers and Children") 

ggplot(all_data, aes(x = mom_slope, y = kid_intercept))+
  geom_smooth(se=F)+
  theme_classic()+
  labs(title = "Relationship between Mother's Slope and Child's Intercept") 

ggplot(all_data, aes(x=mom_slope, y=kid_intercept, color=race))+
  geom_boxplot()+
  facet_wrap(~race)+
  theme_classic()+
   labs(title = "Relationship between Mother's Slope and Child's Intercept", subtitle = "Group by Ethnicity") 



# How to define mother's speech as "more/less diverse"?
# Also, what effect does mother's DIVERSITY have on kid's INTERCEPT?

## 1) 1sd ± mean of mothers' intercept
# high:28 moms; median:32; low: 6;
all_data %>%
  ungroup(.) %>%
  mutate(mean = mean(mom_intercept),
         sd = sd(mom_intercept)) %>%
  mutate(rank = ifelse(mom_intercept < mean-sd, 0, 
                       ifelse( mom_intercept < mean, 1,2)),
         rank = as.factor(rank)) %>%
  ggplot(.,aes(x=kid_intercept, color=rank))+
  geom_density()+
  theme_classic()

## 2) look at slope: to what degree mother change the way they talk
# high:10 moms; median:47; low: 9
all_data %>%
  ungroup()%>%
  mutate(mean = mean(mom_slope),
         sd = sd(mom_slope)) %>%
  mutate(rank = ifelse(mom_slope <= mean-sd, 0,
                       ifelse(mean+sd >mom_slope, 1,2)),
         rank = as.factor(rank)) %>%
  ggplot(.,aes(x=kid_intercept, color=rank))+
  geom_density()+
  theme_classic()


## 3) difference between mom's intercept and kid's intercept
# high:32 moms; lower: 34 moms
all_data %>%
  ungroup()%>%
  mutate(dif = mom_intercept - kid_intercept) %>%
  mutate(mean = mean(dif),
        rank = ifelse(dif > mean, 1, 0),
        rank = as.factor(rank)) %>%
  ggplot(.,aes(x=kid_intercept, color=rank))+
  geom_density()+
  facet_wrap(~sex)+
  theme_classic()



# General growth trajectory varies by mother's diversity of speech
# shows dif effects on boys and girls
all_data %>%
  ungroup()%>%
 mutate(mean = mean(mom_intercept),
        sd = sd(mom_intercept)) %>%
  mutate(rank = ifelse(mom_intercept < mean-sd, 0, 
                       ifelse(mom_intercept < mean, 1,2)),
         rank = as.factor(rank)) %>%
  group_by(subject) %>%
  ggplot(.,aes(x=age, y=kid_mtld, color=rank))+
  geom_smooth(se=F)+
  facet_wrap(~sex)+
  theme_classic()
```  
  
  
## Model3: Child's Slope as Response
```{r}
null2 <- lm(kid_slope ~ 1, data = all_data)
full2 <- lm(kid_slope ~ kid_intercept + mom_slope + mom_intercept + sex + race + income, data = all_data)
step(null2, scope=list(lower=null2, upper=full2), direction="both", na.rm = TRUE)

# summarize Model3 
Model3 <- lm(kid_slope ~ mom_intercept + mom_slope + sex + race + 
    income + kid_intercept, data = all_data) 

summary(Model3)

sjt.lmer(Model3, show.header = TRUE, string.est = "Estimate", 
         string.ci = "Conf. Int.", string.p = "p-value",
         string.dv = "Response", string.pred = "Coefficients",
         p.numeric = F)




# Plot
all_data %>%
  filter(race=="WH") %>%
ggplot(., aes(x = kid_slope, color=sex))+
  geom_density()+
  theme_classic()+
  labs(title = "Variation Among White Children of Different Genders") 

all_data %>%
  ungroup(.)%>%
  ggplot(.,aes(x=race, y=kid_slope, color=sex))+
  geom_boxplot()+
  theme_classic()+
  labs(title = "Variation Among Children of Different Ethnicities") 



# How to define mother's speech as "more/less diverse"?
# Also, what effect does mother's DIVERSITY have on kid's SLOPE?

## 1) 1 SD from mean of mothers' slope
# high: 28 moms; median: 32; low: 6;
all_data %>%
  ungroup()%>%
  mutate(mean = mean(mom_intercept),
         sd = sd(mom_intercept)) %>%
  mutate(rank = ifelse(mom_intercept < mean-sd, 0, 
                       ifelse( mom_intercept < mean, 1,2)),
         rank = as.factor(rank)) %>%
  group_by(subject) %>%
  ggplot(.,aes(x=kid_slope, color=rank))+
  geom_density()+
  theme_classic()

all_data %>%
  ungroup()%>%
  mutate(mean = mean(mom_intercept),
         sd = sd(mom_intercept)) %>%
  mutate(rank = ifelse(mom_intercept < mean-sd, 0, 
                       ifelse( mom_intercept < mean, 1,2)),
         rank = as.factor(rank))%>%
  group_by(subject) %>%
  ggplot(.,aes(x=kid_slope, color=sex))+
  geom_density()+
  facet_grid(.~rank)+
  theme_classic()


## 2) look at slope: to what degree mothers change the way they talk
# high:31 moms; median:35 moms; low:0;
all_data %>%
  ungroup()%>%
  mutate(mean = mean(mom_slope),
         sd = mean(mom_slope)) %>%
  mutate(rank = ifelse(mom_slope < mean-sd, 0, 
                       ifelse(mom_slope < mean, 1,2)),
         rank = as.factor(rank)) %>%
  ggplot(.,aes(x=kid_slope, color=rank))+
  geom_density()+
  theme_classic()

all_data %>%
  ungroup()%>%
  mutate(mean = mean(mom_slope),
         sd = mean(mom_slope)) %>%
  mutate(rank = ifelse(mom_slope < mean-sd, 0, 
                       ifelse(mom_slope < mean, 1,2)),
         rank = as.factor(rank))%>%
  ggplot(.,aes(x=kid_slope, color=sex))+
  geom_density()+
  facet_grid(.~rank)+
  theme_classic()

## 3) difference between mom's intercept and kid's intercept at 20 months
# high:32 moms; median:25; low: 9
all_data %>%
  ungroup()%>%
  mutate(dif = mom_intercept - kid_intercept) %>%
  mutate(mean = mean(dif),
         sd = sd(dif),
        rank = ifelse(dif < mean-sd, 0, 
                      ifelse(dif < mean, 1, 2)),
        rank = as.factor(rank)) %>%
  ggplot(.,aes(x=kid_slope, color=rank))+
  geom_density()+
  theme_classic()

all_data %>%
  ungroup()%>%
  mutate(dif = mom_intercept - kid_intercept) %>%
  mutate(mean = mean(dif),
         sd = sd(dif),
        rank = ifelse(dif < mean-sd, 0, 
                      ifelse(dif < mean, 1, 2)),
        rank = as.factor(rank)) %>%
  ggplot(.,aes(x=kid_slope, color=sex))+
  geom_density()+
  facet_grid(.~rank)+
  theme_classic()
```


## Model 4: Mother's intercept as Response
```{r}
# Mothers talk differently to boys and girls
null3 <- lm(mom_intercept ~ 1 , data = all_data)
full3 <- lm(mom_intercept ~ kid_slope + kid_intercept + sex + race + income, data = all_data)
step(null3, scope=list(lower=null3, upper=full3), direction="both", na.rm = TRUE)

# summarize Model 4
Model4 <- lm(formula = mom_intercept ~ kid_intercept + sex + race + kid_slope + 
    income, data = all_data)

summary(Model4)

sjt.lmer(Model4, show.header = TRUE, string.est = "Estimate", 
         string.ci = "Conf. Int.", string.p = "p-value",
         string.dv = "Response", string.pred = "Coefficients",
         p.numeric = F)

# Plot
# 32 girls, 34 boys
ggplot(all_data2, aes(x=mom_intercept, color=sex))+
  geom_density()+
  theme_classic()+
  labs(title = "Variation of Mother's Intercept among 
Children of Different Genders") 

## this variation is not mediated by income
all_data %>%
  ggplot(., aes(x=mom_intercept, color=sex))+
  geom_density()+
  facet_wrap(~income)+
  theme_classic()
```

